openapi: 3.0.3
info:
  title: OOSA API
  description: This is OOSA's API
  version: "1.0.0"
servers:
  - url: https://api-dev.oosa.life 
    description: OOSA's Dev API
  - url: http://oosa_user:6080
    description: OOSA_USER_SERVICE
  - url: http://oosa_rewild:6080
    description: OOSA_REWILD_SERVICE

components:
  securitySchemes:
    Bearer:
      type: apiKey
      in: header
      name: Authorization